// Auto-generated by tauri-specta. DO NOT EDIT.
// Run `cargo test export_specta_bindings` to regenerate.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async addRepository(path: string) : Promise<Result<Repository, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_repository", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeRepository(repoId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_repository", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRepositories() : Promise<Result<Repository[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_repositories") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listBranches(repoId: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_branches", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cloneRepository(url: string, path: string) : Promise<Result<Repository, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clone_repository", { url, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async initRepository(path: string, name: string) : Promise<Result<Repository, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("init_repository", { path, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createWorkspace(request: CreateWorkspaceRequest) : Promise<Result<WorkspaceInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_workspace", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWorkspaces() : Promise<Result<WorkspaceInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_workspaces") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async archiveWorkspace(workspaceId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("archive_workspace", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteWorkspace(workspaceId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_workspace", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listArchivedWorkspaces() : Promise<Result<WorkspaceInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_archived_workspaces") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restoreWorkspace(workspaceId: string) : Promise<Result<WorkspaceInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_workspace", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSparseDirs(workspaceId: string, dirs: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_sparse_dirs", { workspaceId, dirs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateWorkspaceNotes(workspaceId: string, notes: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_workspace_notes", { workspaceId, notes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameWorkspace(workspaceId: string, name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_workspace", { workspaceId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setWorkspacePinned(workspaceId: string, pinned: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_workspace_pinned", { workspaceId, pinned }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async linkWorkspaces(workspaceId: string, linkedWorkspaceId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("link_workspaces", { workspaceId, linkedWorkspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unlinkWorkspaces(workspaceId: string, linkedWorkspaceId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlink_workspaces", { workspaceId, linkedWorkspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLinkedWorkspaces(workspaceId: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_linked_workspaces", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startSpotlight(workspaceId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_spotlight", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopSpotlight(workspaceId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_spotlight", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendMessage(request: SendMessageRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_message", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async respondToPermission(workspaceId: string, approved: boolean, updatedPermissions: JsonValue | null, decisionClassification: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("respond_to_permission", { workspaceId, approved, updatedPermissions, decisionClassification }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return any pending permission request for a workspace.
 * Called by the frontend on resubscribe (e.g. after HMR) to recover lost UI state.
 */
async getPendingPermission(workspaceId: string) : Promise<Result<FrontendStreamEvent | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_pending_permission", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendFollowupMessage(workspaceId: string, message: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_followup_message", { workspaceId, message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopAgent(workspaceId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_agent", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAgentStatus(workspaceId: string) : Promise<Result<AgentInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_agent_status", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearSession(workspaceId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_session", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveChatMessage(message: ChatMessage) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_chat_message", { message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listChatMessages(workspaceId: string) : Promise<Result<ChatMessage[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_chat_messages", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearChatMessages(workspaceId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_chat_messages", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchChatMessages(query: string, workspaceId: string | null) : Promise<Result<ChatMessageSearchResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_chat_messages", { query, workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCheckpoints(workspaceId: string) : Promise<Result<Checkpoint[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_checkpoints", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async revertToCheckpoint(workspaceId: string, checkpointId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("revert_to_checkpoint", { workspaceId, checkpointId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDiff(workspaceId: string) : Promise<Result<DiffResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_diff", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFileDiff(workspaceId: string, filePath: string) : Promise<Result<FileDiffContent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_diff", { workspaceId, filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGitLog(workspaceId: string, maxCount: number | null) : Promise<Result<GitLogEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_git_log", { workspaceId, maxCount }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRepoDiff(repoId: string) : Promise<Result<DiffResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_repo_diff", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRepoFileDiff(repoId: string, filePath: string) : Promise<Result<FileDiffContent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_repo_file_diff", { repoId, filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFilePatch(workspaceId: string, filePath: string, isUntracked: boolean | null) : Promise<Result<FilePatchPreview, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_patch", { workspaceId, filePath, isUntracked }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRepoFilePatch(repoId: string, filePath: string, isUntracked: boolean | null) : Promise<Result<FilePatchPreview, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_repo_file_patch", { repoId, filePath, isUntracked }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRepoDirectories(repoId: string, depth: number | null) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_repo_directories", { repoId, depth }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWorkspaceFiles(workspaceId: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_workspace_files", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRepoFiles(repoId: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_repo_files", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readWorkspaceFile(workspaceId: string, filePath: string) : Promise<Result<FileContent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_workspace_file", { workspaceId, filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readRepoFile(repoId: string, filePath: string) : Promise<Result<FileContent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_repo_file", { repoId, filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadTypeDefinitions(workspaceId: string | null, repoId: string | null) : Promise<Result<TypeDefinitions, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_type_definitions", { workspaceId, repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeWorkspaceFile(workspaceId: string, filePath: string, content: string, formatOnSave: boolean) : Promise<Result<WriteFileResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_workspace_file", { workspaceId, filePath, content, formatOnSave }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeRepoFile(repoId: string, filePath: string, content: string, formatOnSave: boolean) : Promise<Result<WriteFileResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_repo_file", { repoId, filePath, content, formatOnSave }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read an arbitrary file and return its contents as a base64 data URL.
 * Used for displaying dropped image previews in the chat UI.
 */
async readFileBase64(filePath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_file_base64", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save base64-encoded image data to a temporary file and return the absolute path.
 * Used for clipboard paste support in the chat composer.
 */
async saveClipboardImage(data: string, mimeType: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_clipboard_image", { data, mimeType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startDiffWatcher(contextId: string, contextType: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_diff_watcher", { contextId, contextType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopDiffWatcher(contextId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_diff_watcher", { contextId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBranchStatus(workspaceId: string) : Promise<Result<BranchStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_branch_status", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchUpstream(workspaceId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_upstream", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pullRebase(workspaceId: string) : Promise<Result<PullResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pull_rebase", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pullMerge(workspaceId: string) : Promise<Result<PullResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pull_merge", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConflictedFiles(workspaceId: string) : Promise<Result<ConflictedFile[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_conflicted_files", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConflictContent(workspaceId: string, filePath: string) : Promise<Result<ConflictContent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_conflict_content", { workspaceId, filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveConflict(workspaceId: string, filePath: string, strategy: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_conflict", { workspaceId, filePath, strategy }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async abortMergeCmd(workspaceId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("abort_merge_cmd", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async continueMerge(workspaceId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("continue_merge", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async crossWorktreeDiff(workspaceId: string, linkedWorkspaceId: string) : Promise<Result<DiffResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cross_worktree_diff", { workspaceId, linkedWorkspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCrossWorktreeFileDiff(workspaceId: string, linkedWorkspaceId: string, filePath: string) : Promise<Result<FileDiffContent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_cross_worktree_file_diff", { workspaceId, linkedWorkspaceId, filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pushWorkspace(workspaceId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("push_workspace", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listStashes(workspaceId: string) : Promise<Result<StashEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_stashes", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createStash(workspaceId: string, message: string | null, includeUntracked: boolean | null) : Promise<Result<StashEntry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_stash", { workspaceId, message, includeUntracked }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applyStash(workspaceId: string, index: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_stash", { workspaceId, index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async popStash(workspaceId: string, index: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pop_stash", { workspaceId, index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dropStash(workspaceId: string, index: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("drop_stash", { workspaceId, index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showStash(workspaceId: string, index: number) : Promise<Result<StashDetail, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_stash", { workspaceId, index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runScript(workspaceId: string, scriptKind: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_script", { workspaceId, scriptKind }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopScript(workspaceId: string, scriptKind: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_script", { workspaceId, scriptKind }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runRepoScript(repoId: string, scriptKind: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_repo_script", { repoId, scriptKind }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopRepoScript(repoId: string, scriptKind: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_repo_script", { repoId, scriptKind }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRepoSettings(repoId: string) : Promise<Result<RepoSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_repo_settings", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateRepoSettings(repoId: string, settings: RepoSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_repo_settings", { repoId, settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createTerminal(workspaceId: string, cols: number, rows: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_terminal", { workspaceId, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeTerminal(terminalId: string, data: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_terminal", { terminalId, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resizeTerminal(terminalId: string, cols: number, rows: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resize_terminal", { terminalId, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeTerminal(terminalId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_terminal", { terminalId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createRepoTerminal(repoId: string, cols: number, rows: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_repo_terminal", { repoId, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createPr(request: CreatePrRequest) : Promise<Result<PrInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_pr", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPrInfo(workspaceId: string) : Promise<Result<PrInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_pr_info", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPrChecks(workspaceId: string) : Promise<Result<PrCheck[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_pr_checks", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pushChanges(workspaceId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("push_changes", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fixFailingChecks(workspaceId: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fix_failing_checks", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mergePr(workspaceId: string, mergeMethod: string | null) : Promise<Result<MergeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("merge_pr", { workspaceId, mergeMethod }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPrReviews(workspaceId: string) : Promise<Result<PrReview[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_pr_reviews", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPrReviewComments(workspaceId: string) : Promise<Result<PrComment[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_pr_review_comments", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches PR info, checks, reviews, and comments.
 */
async getPrFullData(workspaceId: string) : Promise<Result<PrFullData, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_pr_full_data", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches reviews and comments.
 */
async getReviewsAndComments(workspaceId: string) : Promise<Result<ReviewsAndComments, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_reviews_and_comments", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRepoPrs(repoId: string) : Promise<Result<PrListItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_repo_prs", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRepoIssues(repoId: string) : Promise<Result<IssueListItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_repo_issues", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPrDetails(repoId: string, prNumber: number) : Promise<Result<PrDetail, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_pr_details", { repoId, prNumber }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getIssueDetails(repoId: string, issueNumber: number) : Promise<Result<IssueDetail, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_issue_details", { repoId, issueNumber }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWorkflowRuns(workspaceId: string) : Promise<Result<WorkflowRun[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_workflow_runs", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRunJobs(workspaceId: string, runId: number) : Promise<Result<WorkflowJob[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_run_jobs", { workspaceId, runId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRunLogs(workspaceId: string, runId: number, failedOnly: boolean) : Promise<Result<RunLogsResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_run_logs", { workspaceId, runId, failedOnly }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async rerunWorkflow(workspaceId: string, runId: number, failedOnly: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rerun_workflow", { workspaceId, runId, failedOnly }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchLinearIssues(query: string) : Promise<Result<LinearIssue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_linear_issues", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async linkIssueToWorkspace(request: LinkIssueRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("link_issue_to_workspace", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unlinkIssueFromWorkspace(request: UnlinkIssueRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlink_issue_from_workspace", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWorkspaceIssues(workspaceId: string) : Promise<Result<WorkspaceIssue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_workspace_issues", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addTodo(request: CreateTodoRequest) : Promise<Result<TodoItem, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_todo", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateTodo(request: UpdateTodoRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_todo", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteTodo(todoId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_todo", { todoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTodos(workspaceId: string) : Promise<Result<TodoItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_todos", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleTodo(todoId: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_todo", { todoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reorderTodos(request: ReorderTodosRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reorder_todos", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTodoSummary(workspaceId: string) : Promise<Result<TodoSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_todo_summary", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSlashCommands(contextId: string, contextType: string) : Promise<Result<SlashCommand[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_slash_commands", { contextId, contextType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSlashCommandContent(workspaceId: string, name: string) : Promise<Result<SlashCommand | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_slash_command_content", { workspaceId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start the Copilot Language Server.
 */
async startCopilot(rootUri: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_copilot", { rootUri }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop the Copilot Language Server.
 */
async stopCopilot() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_copilot") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Trigger GitHub OAuth device flow sign-in.
 */
async copilotSignIn() : Promise<Result<CopilotSignInResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copilot_sign_in") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check Copilot authentication status.
 */
async copilotCheckStatus() : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copilot_check_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Notify Copilot LS that a document was opened.
 */
async copilotDidOpen(event: DocSyncEvent) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copilot_did_open", { event }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Notify Copilot LS that a document changed.
 */
async copilotDidChange(event: DocChangeEvent) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copilot_did_change", { event }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Notify Copilot LS that a document was closed.
 */
async copilotDidClose(uri: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copilot_did_close", { uri }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Request inline completions at a given position.
 */
async copilotComplete(uri: string, line: number, character: number) : Promise<Result<CompletionResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copilot_complete", { uri, line, character }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async indexRepository(repoId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("index_repository", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getIndexingStatus(repoId: string) : Promise<Result<IndexingStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_indexing_status", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listIndexingStatuses() : Promise<Result<IndexingStatus[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_indexing_statuses") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the current Claude permission rules from ~/.claude/settings.json.
 */
async getClaudePermissions() : Promise<Result<ClaudePermissionsResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_claude_permissions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add permission rules to ~/.claude/settings.json.
 * Merges with existing rules (no duplicates).
 */
async addClaudePermissions(rules: string[]) : Promise<Result<ClaudePermissions, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_claude_permissions", { rules }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove permission rules from ~/.claude/settings.json.
 */
async removeClaudePermissions(rules: string[]) : Promise<Result<ClaudePermissions, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_claude_permissions", { rules }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMcpServers(scope: string | null) : Promise<Result<McpServer[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_mcp_servers", { scope }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addMcpServer(request: AddMcpRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_mcp_server", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeMcpServer(request: RemoveMcpRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_mcp_server", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async detectCursorConfig() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_cursor_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importCursorConfig() : Promise<Result<CursorMigrationResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_cursor_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateAppSettings(settings: AppSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_app_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async detectCursorrules(repoId: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_cursorrules", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importCursorrules(repoId: string, overwrite: boolean) : Promise<Result<CursorRulesImportResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_cursorrules", { repoId, overwrite }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLspCatalog() : Promise<Result<LspCatalogEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_lsp_catalog") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listLspPlugins() : Promise<Result<LspPlugin[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_lsp_plugins") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installLspPlugin(request: InstallLspPluginRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_lsp_plugin", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async uninstallLspPlugin(request: UninstallLspPluginRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("uninstall_lsp_plugin", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async detectLspSuggestions(repoPath: string) : Promise<Result<LspSuggestion[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_lsp_suggestions", { repoPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createBookmark(request: CreateBookmarkRequest) : Promise<Result<FileBookmark, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_bookmark", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listBookmarks(repoId: string) : Promise<Result<FileBookmark[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_bookmarks", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateBookmark(bookmarkId: string, request: UpdateBookmarkRequest) : Promise<Result<FileBookmark, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_bookmark", { bookmarkId, request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteBookmark(bookmarkId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_bookmark", { bookmarkId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleBookmark(repoId: string, filePath: string, lineNumber: number) : Promise<Result<FileBookmark | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_bookmark", { repoId, filePath, lineNumber }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createWorkspaceTemplate(request: CreateWorkspaceTemplateRequest) : Promise<Result<WorkspaceTemplate, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_workspace_template", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWorkspaceTemplates(repoId: string) : Promise<Result<WorkspaceTemplate[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_workspace_templates", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateWorkspaceTemplate(templateId: string, request: UpdateWorkspaceTemplateRequest) : Promise<Result<WorkspaceTemplate, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_workspace_template", { templateId, request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteWorkspaceTemplate(templateId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_workspace_template", { templateId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createPrompt(request: CreatePromptRequest) : Promise<Result<Prompt, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_prompt", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPrompts() : Promise<Result<Prompt[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_prompts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePrompt(promptId: string, request: UpdatePromptRequest) : Promise<Result<Prompt, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_prompt", { promptId, request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePrompt(promptId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_prompt", { promptId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createSnippet(request: CreateSnippetRequest) : Promise<Result<Snippet, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_snippet", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSnippets() : Promise<Result<Snippet[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_snippets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSnippet(snippetId: string, request: UpdateSnippetRequest) : Promise<Result<Snippet, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_snippet", { snippetId, request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSnippet(snippetId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_snippet", { snippetId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async detectTestFramework(repoId: string) : Promise<Result<TestRunnerConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_test_framework", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTestRunnerConfig(repoId: string) : Promise<Result<TestRunnerConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_test_runner_config", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveTestRunnerConfig(repoId: string, config: TestRunnerConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_test_runner_config", { repoId, config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runTests(contextId: string, contextType: string, fileFilter: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_tests", { contextId, contextType, fileFilter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopTests(contextId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_tests", { contextId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startTestWatch(contextId: string, contextType: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_test_watch", { contextId, contextType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopTestWatch(contextId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_test_watch", { contextId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTestHistory(repoId: string, limit: number | null) : Promise<Result<TestRunRecord[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_test_history", { repoId, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runCoverage(contextId: string, contextType: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_coverage", { contextId, contextType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pushIpcMetrics(metrics: IpcMetricPayload[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("push_ipc_metrics", { metrics }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pushFrameMetrics(metrics: FrameMetricPayload[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("push_frame_metrics", { metrics }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pushAgentTurnMetric(metric: AgentTurnPayload) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("push_agent_turn_metric", { metric }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pushStreamEvents(events: StreamEventPayload[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("push_stream_events", { events }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async togglePerfMonitor(enabled: boolean) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_perf_monitor", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPerfStatus() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_perf_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getUsageData(workspaceId: string | null, since: string | null) : Promise<Result<UsageDataPoint[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_usage_data", { workspaceId, since }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportWorkspace(options: ExportOptions) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_workspace", { options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startContainer(workspaceId: string) : Promise<Result<ContainerState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_container", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopContainer(workspaceId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_container", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async rebuildContainer(workspaceId: string) : Promise<Result<ContainerState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rebuild_container", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getContainerStatus(workspaceId: string) : Promise<Result<ContainerState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_container_status", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateDevcontainerConfig(workspaceId: string, config: DevContainerConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_devcontainer_config", { workspaceId, config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async detectDevcontainer(repoId: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_devcontainer", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async containerizeRepo(workspaceId: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("containerize_repo", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applyDevcontainerConfig(workspaceId: string, configJson: string, commitToRepo: boolean, devcontainerPath: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_devcontainer_config", { workspaceId, configJson, commitToRepo, devcontainerPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AddMcpRequest = { name: string; command: string; args: string[]; env: Partial<{ [key in string]: string }>; scope: McpScope }
export type AgentExecMode = "host" | "container"
export type AgentInfo = { workspaceId: string; sessionId: string | null; status: AgentStatus; startedAt: string | null; pid: number | null }
export type AgentStatus = "Idle" | "Running" | "Stopping" | { Error: string }
export type AgentTurnPayload = { workspaceId: string; durationMs: number; durationApiMs: number; inputTokens: number; outputTokens: number; cacheReadTokens: number; cacheCreationTokens: number; totalCostUsd: number; numTurns: number; timestamp: number }
export type AgentType = "claude_code" | "codex_cli"
export type AppSettings = { agentType?: AgentType; theme: string; provider: ProviderConfig; systemPromptAdditions: string | null; analyticsEnabled: boolean; experimental: ExperimentalSettings; copilot?: CopilotSettings; linear?: LinearSettings; azureDevops?: AzureDevOpsSettings; claudeContext?: ClaudeContextSettings; customThemes?: CustomTheme[] }
export type AzureDevOpsSettings = { pat: string | null; defaultOrg: string | null }
export type BranchStatus = { branch: string; defaultBranch: string; ahead: number; behind: number; hasUpstream: boolean }
export type ChatMessage = { id: string; workspaceId: string; role: MessageRole; content: ContentBlock[]; timestamp: string; displayText?: string | null; metadata?: ResponseMetadata | null }
export type ChatMessageSearchResult = { messageId: string; workspaceId: string; workspaceName: string; role: string; matchedText: string; timestamp: string }
export type Checkpoint = { id: string; workspaceId: string; sessionId: string; turnIndex: number; refName: string; treeSha: string; commitSha: string; createdAt: string; userMessage: string }
export type ClaudeContextSettings = { enabled: boolean; openaiApiKey: string | null; zillizUri: string | null; zillizToken: string | null }
/**
 * The permissions section of a Claude settings.json file.
 */
export type ClaudePermissions = { allow: string[]; deny: string[] }
/**
 * Response for get_claude_permissions: returns the current allow/deny lists.
 */
export type ClaudePermissionsResponse = { permissions: ClaudePermissions; settingsPath: string }
export type CompletionResult = { items: CopilotCompletion[] }
export type ConflictContent = { path: string; base: string; ours: string; theirs: string; merged: string; language: string }
export type ConflictType = "bothModified" | "deletedByUs" | "deletedByThem" | "addedByBoth" | "bothDeleted" | "unknown"
export type ConflictedFile = { path: string; conflictType: ConflictType }
export type ContainerBackend = "devcontainerCli" | "rawDocker"
export type ContainerState = { workspaceId: string; status: ContainerStatus; containerId: string | null; containerName: string | null; logTail: string[] }
export type ContainerStatus = "none" | "building" | "running" | "stopped" | { error: string }
export type ContentBlock = { type: "text"; text: string } | { type: "toolUse"; id: string; name: string; input: JsonValue } | { type: "toolResult"; tool_use_id: string; content: string } | { type: "image"; media_type: string; data: string }
export type CopilotCompletion = { insertText: string; range: CopilotRange | null; command: JsonValue | null }
export type CopilotPosition = { line: number; character: number }
export type CopilotRange = { start: CopilotPosition; end: CopilotPosition }
export type CopilotSettings = { enabled: boolean }
export type CopilotSignInResult = { status: string; userCode: string | null; verificationUri: string | null; user: string | null }
export type CreateBookmarkRequest = { repoId: string; filePath: string; lineNumber: number; note: string | null; color: string | null }
export type CreatePrRequest = { workspaceId: string; title: string; body: string; draft: boolean | null }
export type CreatePromptRequest = { name: string; content: string; description: string | null; category: string | null; tags: string[] | null }
export type CreateSnippetRequest = { title: string; content: string; language: string | null; description: string | null; tags: string[] | null; source: string | null }
export type CreateTodoRequest = { workspaceId: string; text: string }
export type CreateWorkspaceRequest = { repoId: string; workspaceName: string; branchName: string; sparseDirs: string[] | null; baseBranch: string | null; autoCommit: boolean | null; fetchRemoteBranch: boolean | null; devcontainerConfig: DevContainerConfig | null }
export type CreateWorkspaceTemplateRequest = { repoId: string; name: string; description: string | null; setupScript: string | null; runScript: string | null; archiveScript: string | null; runScriptMode: string | null; envVars: Partial<{ [key in string]: string }> | null; sparseDirs: string[] | null; autoCommit: boolean | null }
export type CursorMigrationResult = { mcpServersFound: number; mcpServersImported: number; rulesFound: boolean }
export type CursorRulesImportResult = { rulesFound: boolean; claudeMdExisted: boolean; written: boolean; claudeMdPath: string }
export type CustomTheme = { id: string; name: string; vars: Partial<{ [key in string]: string }>; baseTheme?: string | null; createdAt: string }
export type DevContainerConfig = { enabled: boolean; backend: ContainerBackend; agentExecMode: AgentExecMode; image: string | null; composeFile: string | null; composeService: string | null; devcontainerPath: string | null; containerWorkspacePath: string | null; extraDockerArgs: string[]; containerEnvVars: Partial<{ [key in string]: string }> }
export type DiffResult = { files: FileDiff[]; totalAdditions: number; totalDeletions: number }
export type DocChangeEvent = { uri: string; version: number; text: string }
export type DocSyncEvent = { uri: string; languageId: string; version: number; text: string }
export type ExperimentalSettings = { spotlightTesting: boolean; agentTeams: boolean; persistentProcesses?: boolean; safeMode?: boolean }
export type ExportOptions = { workspaceId: string; includeChat: boolean; includeTodos: boolean; includeRepoSettings: boolean; includeEnvVars: boolean; includeBookmarks: boolean; includeSnippets: boolean }
export type FileBookmark = { id: string; repoId: string; filePath: string; lineNumber: number; note: string | null; color: string | null; createdAt: string; updatedAt: string }
export type FileContent = { content: string; language: string }
export type FileDiff = { path: string; status: FileStatus; additions: number; deletions: number }
export type FileDiffContent = { path: string; original: string; modified: string; language: string }
export type FilePatchPreview = { path: string; language: string; patch: string; truncated: boolean }
export type FileStatus = "added" | "modified" | "deleted" | { renamed: { from: string } } | "untracked"
export type FrameMetricPayload = { durationMs: number; timestamp: number }
/**
 * Lightweight event emitted to the frontend via Tauri events.
 * We re-serialize from the raw stream to a simpler shape.
 */
export type FrontendStreamEvent = { type: "system"; session_id: string | null; message: string | null } | { type: "assistantText"; text: string } | { type: "toolUse"; id: string; name: string; input: JsonValue } | { type: "toolResult"; tool_use_id: string; content: string } | { type: "assistantImage"; media_type: string; data: string } | { type: "result"; is_error: boolean; result: string | null; session_id: string | null; duration_ms?: number | null; duration_api_ms?: number | null; total_cost_usd?: number | null; num_turns?: number | null; input_tokens?: number | null; output_tokens?: number | null; cache_read_tokens?: number | null; cache_creation_tokens?: number | null } | { type: "permissionRequest"; tool_name: string; input: JsonValue; suggestions?: JsonValue | null }
export type GitLogEntry = { hash: string; full_hash: string; message: string; author: string; timestamp: string }
export type GitProvider = "git_hub" | "azure_dev_ops" | "unknown"
export type IndexingState = "not_indexed" | "indexing" | "indexed" | "error"
export type IndexingStatus = { repoId: string; repoPath: string; status: IndexingState; error: string | null; lastIndexedAt: string | null }
export type InstallLspPluginRequest = { pluginName: string; scope: string }
export type IpcMetricPayload = { command: string; durationMs: number; success: boolean; error: string | null; timestamp: number }
export type IssueDetail = { number: number; title: string; body: string; state: string; labels: string[] }
export type IssueListItem = { number: number; title: string; body: string; state: string; labels: string[] }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type LinearIssue = { id: string; identifier: string; title: string; url: string; stateName: string | null; priority: number | null; teamName: string | null; description: string | null }
export type LinearSettings = { apiKey: string | null }
export type LinkIssueRequest = { workspaceId: string; issueId: string; identifier: string; title: string; url: string }
/**
 * A catalog entry for a known official LSP plugin.
 */
export type LspCatalogEntry = { pluginName: string; language: string; binaryName: string; extensions: string[]; installHint: string }
/**
 * An installed LSP plugin with runtime status.
 */
export type LspPlugin = { name: string; scope: string; enabled: boolean; binaryFound: boolean; binaryName: string; installHint: string }
/**
 * A suggestion for an LSP plugin based on workspace file analysis.
 */
export type LspSuggestion = { pluginName: string; language: string; fileCount: number; binaryName: string; installHint: string }
export type McpScope = "user" | "project"
export type McpServer = { name: string; command: string; args: string[]; env: Partial<{ [key in string]: string }>; scope: McpScope }
export type MergeResult = { success: boolean; message: string; mergeMethod: string }
export type MessageRole = "user" | "assistant" | "system"
export type PrCheck = { name: string; status: string; conclusion: string | null; detailsUrl: string | null; description: string | null }
export type PrComment = { id: number; author: string; body: string; createdAt: string; path: string | null; line: number | null }
export type PrDetail = { number: number; title: string; headBranch: string; baseBranch: string; body: string; state: string; url: string }
export type PrFullData = { info: PrInfo; reviews: PrReview[]; reviewComments: PrComment[] }
export type PrInfo = { workspaceId: string; prNumber: number | null; prUrl: string | null; title: string | null; state: string | null; checks: PrCheck[]; mergeable: string | null }
export type PrListItem = { number: number; title: string; headBranch: string; baseBranch: string; state: string; author: string; url: string }
export type PrReview = { id: number; author: string; state: string; body: string; submittedAt: string }
export type Prompt = { id: string; name: string; content: string; description: string | null; category: string | null; tags: string[]; sortOrder: number; createdAt: string; updatedAt: string }
export type ProviderConfig = { providerType: ProviderType; envVars: Partial<{ [key in string]: string }> }
export type ProviderType = "Anthropic" | "OpenRouter" | "VercelAIGateway" | "Bedrock" | "Vertex" | "AzureFoundry" | "Custom"
export type PullResult = { success: boolean; message: string; hasConflicts: boolean; conflictedFiles: string[] }
export type RemoveMcpRequest = { name: string; scope: McpScope }
export type ReorderTodosRequest = { workspaceId: string; todoIds: string[] }
export type RepoSettings = { setupScript: string | null; runScript: string | null; archiveScript: string | null; runScriptMode: RunScriptMode; envVars: Partial<{ [key in string]: string }>; worktreeBasePath: string | null; providerOverride?: ProviderConfig | null; devcontainer?: DevContainerConfig | null }
export type Repository = { id: string; name: string; path: string; defaultBranch: string; 
/**
 * Current checked-out branch, populated at query time.
 */
currentBranch?: string | null; provider?: GitProvider; remoteUrl?: string | null }
export type ResponseMetadata = { durationMs?: number | null; durationApiMs?: number | null; totalCostUsd?: number | null; numTurns?: number | null; inputTokens?: number | null; outputTokens?: number | null; cacheReadTokens?: number | null; cacheCreationTokens?: number | null }
export type ReviewsAndComments = { reviews: PrReview[]; reviewComments: PrComment[] }
export type RunLogsResult = { logs: string; truncated: boolean; taskLogs: TaskLog[] | null }
export type RunScriptMode = "concurrent" | "nonconcurrent"
export type SendMessageRequest = { 
/**
 * Either workspace_id or repo_id must be provided.
 */
workspaceId: string | null; repoId: string | null; message: string; 
/**
 * Optional model override (e.g. "sonnet", "opus", "haiku", or a full model ID).
 */
model: string | null; 
/**
 * When true, disable extended thinking for this message.
 */
disableThinking: boolean | null; 
/**
 * When true, disable plan mode for this message.
 */
disablePlanMode: boolean | null }
export type SlashCommand = { name: string; source: SlashCommandSource; description: string; content: string }
export type SlashCommandSource = "global" | "project" | "plugin"
export type Snippet = { id: string; title: string; content: string; language: string | null; description: string | null; tags: string[]; source: string | null; createdAt: string; updatedAt: string }
export type StashDetail = { index: number; message: string; files: StashFileStat[]; patch: string }
export type StashEntry = { index: number; message: string; branch: string; timestamp: string }
export type StashFileStat = { path: string; additions: number; deletions: number }
export type StreamEventPayload = { workspaceId: string; eventType: string; details: string | null; source: string; timestamp: number }
export type TaskLog = { taskName: string; jobName: string; logContent: string; status: string; conclusion: string | null }
export type TestFramework = "vitest" | "jest" | "pytest" | "cargotest" | "gotest" | "custom"
export type TestRunRecord = { id: string; repoId: string; ranAt: string; total: number; passed: number; failed: number; skipped: number; durationMs: number }
export type TestRunnerConfig = { framework: TestFramework | null; testCommand: string | null; testFileCommand: string | null; workingDir: string | null; coverageCommand: string | null }
export type TodoItem = { id: string; workspaceId: string; text: string; completed: boolean; sortOrder: number }
export type TodoSummary = { total: number; completed: number; allCompleted: boolean; items: TodoItem[] }
export type TypeDefFile = { filePath: string; content: string }
export type TypeDefinitions = { tsconfig: string | null; libs: TypeDefFile[] }
export type UninstallLspPluginRequest = { pluginName: string; scope: string }
export type UnlinkIssueRequest = { workspaceId: string; issueId: string }
export type UpdateBookmarkRequest = { note: string | null; color: string | null; lineNumber: number | null }
export type UpdatePromptRequest = { name: string | null; content: string | null; description: string | null; category: string | null; tags: string[] | null }
export type UpdateSnippetRequest = { title: string | null; content: string | null; language: string | null; description: string | null; tags: string[] | null; source: string | null }
export type UpdateTodoRequest = { id: string; workspaceId: string; text: string | null; completed: boolean | null }
export type UpdateWorkspaceTemplateRequest = { name: string | null; description: string | null; setupScript: string | null; runScript: string | null; archiveScript: string | null; runScriptMode: string | null; envVars: Partial<{ [key in string]: string }> | null; sparseDirs: string[] | null; autoCommit: boolean | null }
export type UsageDataPoint = { workspaceId: string; workspaceName: string; timestamp: string; totalCostUsd: number; inputTokens: number; outputTokens: number; cacheReadTokens: number; cacheCreationTokens: number; numTurns: number; durationMs: number }
export type WorkflowJob = { id: number; name: string; status: string; conclusion: string | null; steps: WorkflowStep[] }
export type WorkflowRun = { id: number; name: string; workflowName: string; status: string; conclusion: string | null; event: string; createdAt: string }
export type WorkflowStep = { name: string; status: string; conclusion: string | null }
export type WorkspaceInfo = { id: string; repoId: string; name: string; branch: string; status: WorkspaceStatus; portBase: number; autoCommit: boolean; pinned: boolean; createdAt: string; archivedAt: string | null; devcontainerConfig?: DevContainerConfig | null }
export type WorkspaceIssue = { workspaceId: string; issueId: string; identifier: string; title: string; url: string; linkedAt: string }
export type WorkspaceStatus = "Creating" | "Active" | "Archived" | { Error: string }
export type WorkspaceTemplate = { id: string; repoId: string; name: string; description: string | null; setupScript: string | null; runScript: string | null; archiveScript: string | null; runScriptMode: string; envVars: Partial<{ [key in string]: string }>; sparseDirs: string[] | null; autoCommit: boolean; createdAt: string; updatedAt: string }
export type WriteFileResult = { content: string; language: string; formatted: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	// @ts-expect-error -- generated by tauri-specta, used when commands accept channels
	// eslint-disable-next-line @typescript-eslint/no-unused-vars
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

// @ts-expect-error -- generated by tauri-specta, used when events are defined
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
